apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: udagram-feed-api
  name: udagram-feed-api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: udagram-feed-api
    spec:
      containers:
      - image: emileasow/udagram-feed-api
        name: udagram-feed-api
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always